### ISSUE TITLE
Script fails when installing openssh on High Sierra due to sbin folder missing

### ISSUE THREAD

**Issue by InfiniteLoop90** [fabiomaia/linuxify#10]
When I ran this on macOS High Sierra (MacBook Pro (Retina, 15-inch, Mid 2015)) I got the following error when it was installing `openssh`:

```
==> Downloading https://homebrew.bintray.com/bottles/openssh-7.8p1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssh-7.8p1.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink sbin/sshd
/usr/local/sbin is not writable.

You can try again using:
  brew link openssh
```

Per [this comment](https://github.com/Homebrew/homebrew-php/issues/4527#issuecomment-346483994) it looks like Apple stopped creating the `/usr/local/sbin` by default.
Would it make sense to, as part of this script, create that directory first if it doesn't exist?

**Comment by zmilonas** [comment]
I think this should rather be filed with https://github.com/Homebrew/brew

**Comment by InfiniteLoop90** [comment]
I’ll open an issue for Homebrew instead. Thanks!
