### ISSUE TITLE
linuxify.sh expects ~/.bashrc file

### ISSUE THREAD

**Issue by InfiniteLoop90** [fabiomaia/linuxify#11]
When I ran this on macOS High Sierra (MacBook Pro (Retina, 15-inch, Mid 2015)) I got an error on [this](https://github.com/fabiomaia/linuxify/blob/39fddb114bc703e3507354d2eb04385ee92258a8/linuxify.sh#L81) line.

I didn't have a `~/.bashrc` file on my system but I did have `~/.bash_profile`. Should the script create the `~/.bashrc` file during the install process or source to `~/.bash_profile` instead?

(Side note: It might be helpful to echo what it’s about to do before running a few of the commands so that it’s easier to tell where it failed at.)

**Comment by techwizrd** [comment]
I think this is related to issue https://github.com/fabiomaia/linuxify/issues/2 and I made a comment about this as well: https://github.com/fabiomaia/linuxify/issues/2#issuecomment-421530973
