### ISSUE TITLE
OpenSSL rather than LibreSSL

### ISSUE THREAD

**Issue by maxwedwards** [fabiomaia/linuxify#15]
Have you considered replacing LibreSSL with OpenSSL as part of linuxify?

I had some inconsistencies with LibreSSL making scripts that ran on linux not work on my Mac. Switching to GNU OpenSSL removed these inconsistencies. Unfortunately, I can't remember the specifics.

**Comment by maxwedwards** [comment]
I think I was referring to OpenSSH which I see is installed. Closing issue.

**Comment by fabiomaia** [comment]
I actually did the opposite, I replaced OpenSSL with LibreSSL. Since the heartbleed bug I got the impression that LibreSSL was now generally preferred. Maybe I'm getting that wrong?

> GNU OpenSSL

Did you mean [GnuTLS](https://www.gnutls.org/)? That is GNU's crypto stack.
