### ISSUE TITLE
Consider a Brewfile ?

### ISSUE THREAD

**Issue by nitrocode** [fabiomaia/linuxify#18]
Love your script. Thought I'd share this too.

You can replace the `linuxify_formulas` and the for loop in `linuxify_install` with the following [`Brewfile`](https://github.com/Homebrew/homebrew-bundle#usage):

```
watch
wget
wdiff --with-gettext
gdb
autoconf

# GNU programs whose BSD counterpart is installed in macOS
coreutils
binutils
diffutils
ed --with-default-names
findutils --with-default-names
gawk
gnu-indent --with-default-names
gnu-sed --with-default-names
gnu-tar --with-default-names
gnu-which --with-default-names
grep --with-default-names
gzip
screen

# GNU programs existing in macOS which are outdated
bash
emacs
gpatch
less
m4
make --with-default-names
nano
bison

# BSD programs existing in macOS which are outdated
flex

# Other common/preferred programs in GNU/Linux distributions
libressl
file-formula
git
openssh
perl
python
rsync
unzip
vim --override-system-vi
```

and with the following line `brew install` and it should pick up the `Brewfile` correctly

**Comment by fabiomaia** [comment]
That's cool but writing the explicit for loop allows me to traverse the list in reverse order to uninstall formulas in the order reverse to which they were installed (which is nice if the list of formulas is written such that any formula's dependencies come before it).
