### ISSUE TITLE
Deprecated options

### ISSUE THREAD

**Issue by elhardoum** [fabiomaia/linuxify#19]
```--with-default-names``` and ```--with-gettext``` flags seem to have been deprecated in Homebrew and it no longer replaces the default binaries as it prefixes them with `g` instead, so for example `/usr/bin/sed` remains untouched while it installs `/usr/local/bin/gsed`..

I tried aliasing `sed` with `gsed`, but it is limited to the Shell, e.g it won't work with commands that skip Shells and execute binaries like `xargs`.

I don't know if there's a solution for this, I might just downgrade `homebrew`.

Thanks for the awesome library!

**Comment by fabiomaia** [comment]
Huh, I'll look at this. Thanks!

**Comment by fabiomaia** [comment]
Things should work now. Could you give it a try?

**Comment by elhardoum** [comment]
Seems to be working now. Thanks for the update! =)
