### ISSUE TITLE
source ~/.linuxify

### ISSUE THREAD

**Issue by fabiomaia** [fabiomaia/linuxify#2]
For everything to work correctly, the script adds `source ~/.linuxify` to `~/.bashrc`. But this assumes:

1. that the user is using `bash`
2. that `~/.bashrc` does not use commands that will only work after the `$PATH` has been patched (e.g.  `export MAKEFLAGS="-j$(nproc)"` will fail if declared before `source ~/.linuxify` because `nproc` is not yet in the `$PATH`)

Should the script continue to try to add `source ~/.linuxify` to `~/.bashrc`.  like this or should the users be responsible for handling this stitching themselves?

**Comment by zmilonas** [comment]
I think appending something to users' profile is kind of unwanted.

If user is competent enough to run this script, they're competent enough to add it to their profile accordingly

**Comment by azah** [comment]
Plenty of things append an install with instructions to "add <X> to your ~/.bashrc or equivalent". Even if it supported my shell (`zsh`), automatically appending would be annoying because I structure my dotfiles in a particular way, etc.

**Comment by fabiomaia** [comment]
> automatically appending would be annoying because I structure my dotfiles in a particular way, etc.

Yeah that's very true. I didn't like it much either. But I still stuck to it in the spirit of an automagical one-step install.

I'll probably change this tonight.

**Comment by techwizrd** [comment]
I'll add that I'm using `fish`, so it'd probably be better to add an instruction at the end of the install requesting the user add `. linuxify.sh`/`source linuxify.sh` to their `.bashrc`/`.zshrc`/`config.fish`/etc.

**Comment by fabiomaia** [comment]
Alright I've changed the behavior of the script in https://github.com/fabiomaia/linuxify/commit/9140a9c4da69994f753c9a5159133d18686b4fd6

Any comments?
