### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by pnodet** [fabiomaia/linuxify#23]
Has of Catalina, zsh is now the default shell instead of bash.

However using linuxify switches back to bash, maybe it could be on option rather than being automatic ?

**Comment by pnodet** [comment]
Those lines:

# Change default shell to brew-installed /usr/local/bin/bash
    grep -qF '/usr/local/bin/bash' /etc/shells || echo '/usr/local/bin/bash' | sudo tee -a /etc/shells > /dev/null
    chsh -s /usr/local/bin/bash

**Comment by fabiomaia** [comment]
Thanks for letting me know this! I'm not currently running macOS, so I was unaware. I'll probably go back to macOS next week though, so I'll take another look.

I think I'll just up the requirements to Catalina and assume zsh.

**Comment by cwr31** [comment]
facing same issue, thanks for your job

**Comment by curusarn** [comment]
Maybe it would be best to detect which shell is set as login and honor the setting automatically. What do you think?

**Comment by fabiomaia** [comment]
I just merged the fix by @stephanGarland which should fix this :)
